#!/bin/bash

function toggle() {
	echo pause|nc -q0 127.0.0.1 1938
}

function tts() {
	s=$(echo state|nc -q2 127.0.0.1 1938|cut -d',' -f2|cut -d':' -f2|cut -d'"' -f2)
	[ "$s" -eq 0 ] && toggle
  mpv 2>1 >/dev/null --quiet tts.wav
	[ "$s" -eq 0 ] && toggle
}

cd /var/lib/musicbotd
[ ! -f tts.wav ] && >tts.wav
inotifywait -qme close_write tts.wav|while read; do tts; done
